// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  eventId: __t.string().name("event_id"),
  marketId: __t.u64().name("market_id"),
  agentIdentity: __t.identity().name("agent_identity"),
  agentName: __t.string().name("agent_name"),
  kind: __t.string(),
  reasoning: __t.string(),
  probability: __t.f64(),
  ts: __t.timestamp(),
});
