// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  marketId: __t.u64().name("market_id"),
  outcomeId: __t.u64().name("outcome_id"),
  trader: __t.identity(),
  shares: __t.f64(),
  cost: __t.f64(),
  probAfter: __t.f64().name("prob_after"),
  ts: __t.timestamp(),
});
