// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const MarketPriceHistory = __t.object("MarketPriceHistory", {
  id: __t.u64(),
  marketId: __t.u64(),
  outcomeId: __t.u64(),
  prob: __t.f64(),
  ts: __t.timestamp(),
});
export type MarketPriceHistory = __Infer<typeof MarketPriceHistory>;

export const Markets = __t.object("Markets", {
  id: __t.u64(),
  eventId: __t.string(),
  question: __t.string(),
  status: __t.string(),
  b: __t.f64(),
  createdAt: __t.timestamp(),
});
export type Markets = __Infer<typeof Markets>;

export const Outcomes = __t.object("Outcomes", {
  id: __t.u64(),
  marketId: __t.u64(),
  label: __t.string(),
  q: __t.f64(),
});
export type Outcomes = __Infer<typeof Outcomes>;

export const Positions = __t.object("Positions", {
  id: __t.u64(),
  key: __t.string(),
  owner: __t.identity(),
  marketId: __t.u64(),
  outcomeId: __t.u64(),
  shares: __t.f64(),
});
export type Positions = __Infer<typeof Positions>;

export const Trades = __t.object("Trades", {
  id: __t.u64(),
  marketId: __t.u64(),
  outcomeId: __t.u64(),
  trader: __t.identity(),
  shares: __t.f64(),
  cost: __t.f64(),
  probAfter: __t.f64(),
  ts: __t.timestamp(),
});
export type Trades = __Infer<typeof Trades>;

export const Users = __t.object("Users", {
  identity: __t.identity(),
  balance: __t.f64(),
  createdAt: __t.timestamp(),
});
export type Users = __Infer<typeof Users>;

