// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import PlaceTradeReducer from "../place_trade_reducer";
import SeedDemoReducer from "../seed_demo_reducer";

export type PlaceTradeParams = __Infer<typeof PlaceTradeReducer>;
export type SeedDemoParams = __Infer<typeof SeedDemoReducer>;

